
const fbData = [
    {
        key:0,
        id: 'qg2124',
        email: 'fqqge@asg.asd',
        content: '안녕하세요 내용입니다.내용입니다.',
        datetime: '2015-02-02',
        commentCount: 123,
        heartCount: 456,
        commentIcon: require(`../svg/comment-icon.svg`),
        commentIcon1: require(`../svg/comment-iconOn.svg`),
        heart: require(`../svg/heart.svg`),
        heart1: require(`../svg/heartOn.svg`),
        toggleComment: false,
        toggleHeart: false,
        toggleFollow: false,
        followColor: '#A49FBA',
        followColorOn: '#F1AD39'
    },
    {   
        key:1,
        id: 'asd123',
        email: 'asd123@asd.asd',
        content: '안녕하세요 내용입니다.',
        datetime: '2015-02-02',
        commentCount: 123,
        heartCount: 456,
        commentIcon1: require(`../svg/comment-iconOn.svg`),
        commentIcon: require(`../svg/comment-icon.svg`),
        heart1: require(`../svg/heartOn.svg`),
        heart: require(`../svg/heart.svg`),
        toggleComment: false,
        toggleHeart: false,
        toggleFollow: false,
        followColor: '#A49FBA',
        followColorOn: '#F1AD39'
    },
    {
        key:2,
        id: 'asd123',
        email: 'asd123@asd.asd',
        content: '안녕하세요 내용입니다.',
        datetime: '2015-02-02',
        commentCount: 123,
        heartCount: 456,
        commentIcon1: require(`../svg/comment-iconOn.svg`),
        commentIcon: require(`../svg/comment-icon.svg`),
        heart1: require(`../svg/heartOn.svg`),
        heart: require(`../svg/heart.svg`),
        toggleComment: false,
        toggleHeart: false,
        toggleFollow: false,
        followColor: '#A49FBA',
        followColorOn: '#F1AD39'
    },
    {
        key:3,
        id: 'asd123',
        email: 'asd123@asd.asd',
        content: '안녕하세요 내용입니다.',
        datetime: '2015-02-02',
        commentCount: 123,
        heartCount: 456,
        commentIcon1: require(`../svg/comment-iconOn.svg`),
        commentIcon: require(`../svg/comment-icon.svg`),
        heart1: require(`../svg/heartOn.svg`),
        heart: require(`../svg/heart.svg`),
        toggleComment: false,
        toggleHeart: false,
        toggleFollow: false,
        followColor: '#A49FBA',
        followColorOn: '#F1AD39'
    },
];

export default fbData;